[general]
live_config_reload = true

[colors.primary]
background = "#000000"

[env]
LANG = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

#[font.non_ascii]
#family = "Agave Nerd Font"
#style = "Regular"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
chars = '\p'
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = '\n'
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.40

blur = true
